package com.example.accessing_data;

// importing annotations to indicate which java objects the JPA should look for when querying the database
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

// this annotation indicates that the class is an entity for the JPA to look for 
@Entity
public class Doctor {

    // this annotation indicates that the id value of the class is the ID that the JPA should look for
    @Id
    // the id is automatically generated by this annotation, and no integer has to be passed into the constructor
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Long id;

    private String firstName;
    private String lastName;

    // the class has 2 constructors - the protected one exists for the JPA to reference the class
    protected Doctor() {}

    // this constructor is the one used by the program to create instances of the Doctor to be stored in the database
    public Doctor(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }

    @Override
    public String toString() {
        return String.format(
            "Doctor[id=%d, firstName='%s', lastName='%s']",
            id, firstName, lastName
        );
    }

    public Long getId() {
        return id;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

}
